import os
import sys
import tempfile
import subprocess
from pathlib import Path
import telebot

os.environ.setdefault("OMP_NUM_THREADS", "2")
os.environ.setdefault("MKL_NUM_THREADS", "2")
os.environ.setdefault("TOKENIZERS_PARALLELISM", "false")
os.environ.setdefault("HF_HUB_ENABLE_HF_TRANSFER", "0")

BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
if not BOT_TOKEN:
    print("ERROR: TELEGRAM_BOT_TOKEN environment variable is missing!")
    sys.exit(1)

bot = telebot.TeleBot(BOT_TOKEN)

MODEL_REPO_ID = os.getenv("MODEL_REPO_ID", "OpenMOSS-Team/MOSS-TTS-Nano-100M")
CODEC_REPO_ID = os.getenv("CODEC_REPO_ID", "OpenMOSS-Team/MOSS-Audio-Tokenizer-Nano")

def synthesize(text: str, ref_audio_path: str = None) -> str:
    text = (text or "").strip()
    if not text:
        text = "Hello! This is a speech synthesis test generated by MOSS TTS Nano."
    
    with tempfile.NamedTemporaryFile(suffix=".wav", delete=False) as tmp_fh:
        tmp_path = Path(tmp_fh.name)
    
    mode = "voice_clone" if ref_audio_path else "continuation"

    command = [
        sys.executable,
        "-m",
        "infer",
        "--checkpoint",
        MODEL_REPO_ID,
        "--audio-tokenizer-pretrained-name-or-path",
        CODEC_REPO_ID,
        "--mode",
        mode,
        "--device",
        "cpu",
        "--dtype",
        "float32",
        "--disable-wetext-processing",
        "--output-audio-path",
        str(tmp_path),
        "--text",
        text,
    ]

    if ref_audio_path:
        command.extend(["--prompt-audio-path", str(ref_audio_path)])

    subprocess.run(
        command,
        check=True,
        capture_output=True,
        text=True,
        env=os.environ.copy(),
    )
    return str(tmp_path)

@bot.message_handler(commands=['start', 'help'])
def send_welcome(message):
    welcome_text = (
        "🎙️ **MOSS TTS Nano Telegram Bot**\n\n"
        "1️⃣ **Text-to-Speech:** Send any text message and I will convert it into speech audio.\n"
        "2️⃣ **Voice Cloning:** Send a voice note or audio file with a text **caption** to clone the voice for your custom text!"
    )
    bot.reply_to(message, welcome_text, parse_mode="Markdown")

@bot.message_handler(content_types=['voice', 'audio'])
def handle_voice_cloning(message):
    text = message.caption
    if not text or not text.strip():
        text = "Hello! This is a voice cloning speech test using MOSS TTS Nano."

    status_msg = bot.reply_to(message, "🔄 Processing audio and cloning voice... Please wait.")
    
    ref_audio_file = None
    generated_wav = None
    try:
        file_info = bot.get_file(message.voice.file_id if message.voice else message.audio.file_id)
        downloaded_file = bot.download_file(file_info.file_path)

        with tempfile.NamedTemporaryFile(suffix=".ogg", delete=False) as tmp_ref:
            tmp_ref.write(downloaded_file)
            ref_audio_file = tmp_ref.name

        generated_wav = synthesize(text, ref_audio_path=ref_audio_file)

        with open(generated_wav, 'rb') as audio:
            bot.send_voice(message.chat.id, audio, caption="✨ Generated using MOSS TTS Nano (Voice Clone)")

        bot.delete_message(message.chat.id, status_msg.message_id)

    except Exception as e:
        print(f"Error: {e}")
        bot.reply_to(message, f"❌ An error occurred: {str(e)[:200]}")
    finally:
        if ref_audio_file and os.path.exists(ref_audio_file):
            os.remove(ref_audio_file)
        if generated_wav and os.path.exists(generated_wav):
            os.remove(generated_wav)

@bot.message_handler(func=lambda message: True)
def handle_text_to_speech(message):
    text = message.text
    if not text or text.startswith('/'):
        return

    status_msg = bot.reply_to(message, "⚙️ Generating speech using MOSS TTS Nano... Please wait.")
    
    generated_wav = None
    try:
        generated_wav = synthesize(text)
        with open(generated_wav, 'rb') as audio:
            bot.send_voice(message.chat.id, audio, caption="😍 Output")
        bot.delete_message(message.chat.id, status_msg.message_id)
    except Exception as e:
        print(f"Error: {e}")
        bot.reply_to(message, f"❌ An error occurred: {str(e)[:200]}")
    finally:
        if generated_wav and os.path.exists(generated_wav):
            os.remove(generated_wav)

if __name__ == "__main__":
    bot.polling(non_stop=False, timeout=10)
